/* eslint-disable */
// AUTO-GENERATED by scripts/bundle-mdx-content.ts — do not edit by hand.
export const rawMdxBySlug: Record<string, string> = {
  "sample-post-one": `---
title: "Sample Post: Shipping a Design System Incrementally"
description: "Placeholder post exercising the blog pipeline — headings, code blocks with titles, and inline code."
date: "2026-07-20"
author: "Huỳnh Sang"
published: true
category: "Placeholder"
readTime: "4 min read"
---

{/* PLACEHOLDER — replace with a real post before publishing. */}

Design systems fail when they are treated as big-bang rewrites. This placeholder walks through the incremental approach with a few code samples.

## Start With Tokens

Tokens are the smallest contract between design and code:

\`\`\`css title="globals.css"
:root {
  --background: oklch(1 0 0);
  --foreground: oklch(0.21 0.01 260);
}
\`\`\`

Use \`var(--background)\` instead of raw palette values everywhere.

## Then Primitives

1. Port one primitive at a time.
2. Keep the API surface identical.
3. Verify with visual diffs.

### Inline code matters too

Helpers like \`cn()\` keep class composition readable.
`,
  "sample-post-two": `---
title: "Sample Post: Notes on Blog Infrastructure"
description: "Placeholder post exercising tables, blockquotes, and external links in the MDX pipeline."
date: "2026-07-05"
author: "Huỳnh Sang"
published: true
category: "Placeholder"
---

{/* PLACEHOLDER — replace with a real post before publishing. */}

A quick tour of the pieces that make this blog work.

## The Pipeline

| Stage  | Tool                                     |
| ------ | ---------------------------------------- |
| Parse  | yaml frontmatter + remark                |
| Render | precompiled HTML (Workers-safe, no eval) |
| Slugs  | rehype-slug heading ids                  |

> Good infrastructure disappears. You notice it only when it breaks.

## References

Read the [Next.js documentation](https://nextjs.org/docs) for the rendering model.
`
};

/** Precompiled HTML bodies — safe on Cloudflare Workers (no runtime MDX eval). */
export const htmlBySlug: Record<string, string> = {
  "sample-post-one": `<p>{/* PLACEHOLDER — replace with a real post before publishing. */}</p>
<p>Design systems fail when they are treated as big-bang rewrites. This placeholder walks through the incremental approach with a few code samples.</p>
<h2 id="start-with-tokens">Start With Tokens</h2>
<p>Tokens are the smallest contract between design and code:</p>
<pre><code class="language-css">:root {
  --background: oklch(1 0 0);
  --foreground: oklch(0.21 0.01 260);
}
</code></pre>
<p>Use <code>var(--background)</code> instead of raw palette values everywhere.</p>
<h2 id="then-primitives">Then Primitives</h2>
<ol>
<li>Port one primitive at a time.</li>
<li>Keep the API surface identical.</li>
<li>Verify with visual diffs.</li>
</ol>
<h3 id="inline-code-matters-too">Inline code matters too</h3>
<p>Helpers like <code>cn()</code> keep class composition readable.</p>`,
  "sample-post-two": `<p>{/* PLACEHOLDER — replace with a real post before publishing. */}</p>
<p>A quick tour of the pieces that make this blog work.</p>
<h2 id="the-pipeline">The Pipeline</h2>
<table>
<thead>
<tr>
<th>Stage</th>
<th>Tool</th>
</tr>
</thead>
<tbody>
<tr>
<td>Parse</td>
<td>yaml frontmatter + remark</td>
</tr>
<tr>
<td>Render</td>
<td>precompiled HTML (Workers-safe, no eval)</td>
</tr>
<tr>
<td>Slugs</td>
<td>rehype-slug heading ids</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Good infrastructure disappears. You notice it only when it breaks.</p>
</blockquote>
<h2 id="references">References</h2>
<p>Read the <a href="https://nextjs.org/docs">Next.js documentation</a> for the rendering model.</p>`
};
