/* eslint-disable */
// AUTO-GENERATED by scripts/bundle-mdx-content.ts — do not edit by hand.
export const rawMdxBySlug: Record<string, string> = {
  "accordion-with-image-tooltip": `---
title: Accordion with Image Tooltip
date: "2026-01-30"
description: An accordion component with image preview tooltips on hover
published: true
type: "component"
theme: "dark"
image: "/media/craft/accordion-with-image-tooltip-light.mp4"
video: "/media/craft/accordion-with-image-tooltip-light.mp4"
videoDark: "/media/craft/accordion-with-image-tooltip-dark.mp4"
aspect_ratio: 1.6
---

## Accordion with Image Tooltip

An accordion component with image preview tooltips on hover.
`,
  "apple-mega-nav": `---
title: Apple Mega Nav
date: "2026-01-30"
description: A mega navigation menu inspired by Apple's design language
published: true
type: "component"
theme: "dark"
image: "/media/craft/apple-mega-nav-light.mp4"
video: "/media/craft/apple-mega-nav-light.mp4"
videoDark: "/media/craft/apple-mega-nav-dark.mp4"
aspect_ratio: 1.6
---

## Apple Mega Nav

A mega navigation menu inspired by Apple's clean design language.
`,
  "bloom-text": `---
title: Bloom Text
date: "2026-01-30"
description: Text animation with a soft bloom and glow effect
published: true
type: "component"
theme: "dark"
image: "/media/craft/bloom-text-light.mp4"
video: "/media/craft/bloom-text-light.mp4"
videoDark: "/media/craft/bloom-text-dark.mp4"
aspect_ratio: 1.6
---

## Bloom Text

A text animation component with a soft bloom and glow reveal effect.
`,
  "cta-meteor": `---
title: CTA Meteor
date: "2026-01-30"
description: A call-to-action component with a meteor shower animation effect
published: true
type: "component"
theme: "dark"
image: "/media/craft/cta-meteor-light.mp4"
video: "/media/craft/cta-meteor-light.mp4"
videoDark: "/media/craft/cta-meteor-dark.mp4"
aspect_ratio: 1.6
---

## CTA Meteor

A call-to-action component with a meteor shower animation effect.
`,
  "flicker-footer": `---
title: Flicker Footer
date: "2026-01-30"
description: A footer component with a subtle flicker animation effect
published: true
type: "component"
theme: "dark"
image: "/media/craft/flicker-footer-light.mp4"
video: "/media/craft/flicker-footer-light.mp4"
videoDark: "/media/craft/flicker-footer-dark.mp4"
aspect_ratio: 1.6
---

## Flicker Footer

A footer component with a subtle flicker animation effect.
`,
  "hero-bars": `---
title: Hero Bars
date: "2026-01-30"
description: Animated hero section with dynamic bar transitions
published: true
type: "component"
theme: "dark"
image: "/media/craft/hero-bars-light.mp4"
video: "/media/craft/hero-bars-light.mp4"
videoDark: "/media/craft/hero-bars-dark.mp4"
aspect_ratio: 1.6
---

## Hero Bars

An animated hero section with dynamic bar transitions for modern landing pages.
`,
  "hero-mobile-showcase": `---
title: Hero Mobile Showcase
date: "2026-01-30"
description: A mobile-first hero section showcasing app screens with smooth transitions
published: true
type: "component"
theme: "dark"
image: "/media/craft/hero-mobile-showcase-light.mp4"
video: "/media/craft/hero-mobile-showcase-light.mp4"
videoDark: "/media/craft/hero-mobile-showcase-dark.mp4"
aspect_ratio: 1.6
---

## Hero Mobile Showcase

A mobile-first hero section that showcases app screens with smooth transitions.
`,
  "instagram-stories": `---
title: Instagram Stories
date: "2026-01-30"
description: An Instagram-style stories viewer component with progress bars and swipe navigation
published: true
type: "component"
theme: "dark"
image: "/media/craft/instagram-stories-light.mp4"
video: "/media/craft/instagram-stories-light.mp4"
videoDark: "/media/craft/instagram-stories-dark.mp4"
aspect_ratio: 1.6
---

## Instagram Stories

An Instagram-style stories viewer with progress bars and swipe navigation.
`,
  "map-location-picker": `---
title: Map Location Picker
date: "2026-01-30"
description: An interactive map-based location picker component
published: true
type: "component"
theme: "dark"
image: "/media/craft/map-location-picker-light.mp4"
video: "/media/craft/map-location-picker-light.mp4"
videoDark: "/media/craft/map-location-picker-dark.mp4"
aspect_ratio: 1.6
---

## Map Location Picker

An interactive map-based location picker component.
`,
  "models-carousel": `---
title: Models Carousel
date: "2026-01-30"
description: A carousel component designed for showcasing 3D models or product imagery
published: true
type: "component"
theme: "dark"
image: "/media/craft/models-carousel-light.mp4"
video: "/media/craft/models-carousel-light.mp4"
videoDark: "/media/craft/models-carousel-dark.mp4"
aspect_ratio: 1.6
---

## Models Carousel

A carousel component designed for showcasing 3D models or product imagery.
`,
  "project-title-morph": `---
title: Project Title Morph
date: "2026-01-30"
description: A title animation that morphs between project names with smooth transitions
published: true
type: "component"
theme: "dark"
image: "/media/craft/project-title-morph-light.mp4"
video: "/media/craft/project-title-morph-light.mp4"
videoDark: "/media/craft/project-title-morph-dark.mp4"
aspect_ratio: 1.6
---

## Project Title Morph

A title animation that morphs between project names with smooth transitions.
`,
  "scroll-fx-timeline": `---
title: Scroll FX Timeline
date: "2026-01-30"
description: A timeline component with scroll-driven animation effects
published: true
type: "component"
theme: "dark"
image: "/media/craft/scroll-fx-timeline-light.mp4"
video: "/media/craft/scroll-fx-timeline-light.mp4"
videoDark: "/media/craft/scroll-fx-timeline-dark.mp4"
aspect_ratio: 1.6
---

## Scroll FX Timeline

A timeline component with scroll-driven animation effects.
`,
  "scroll-fx": `---
title: Scroll FX
date: "2026-01-30"
description: Scroll-driven visual effects and parallax animations
published: true
type: "component"
theme: "dark"
image: "/media/craft/scroll-fx-light.mp4"
video: "/media/craft/scroll-fx-light.mp4"
videoDark: "/media/craft/scroll-fx-dark.mp4"
aspect_ratio: 1.6
---

## Scroll FX

Scroll-driven visual effects and parallax animations for immersive page experiences.
`,
  "scroll-split-video-gallery": `---
title: Scroll Split Video Gallery
date: "2026-01-30"
description: A split-screen video gallery with scroll-driven transitions
published: true
type: "component"
theme: "dark"
image: "/media/craft/scroll-split-video-gallery-light.mp4"
video: "/media/craft/scroll-split-video-gallery-light.mp4"
videoDark: "/media/craft/scroll-split-video-gallery-dark.mp4"
aspect_ratio: 1.6
---

## Scroll Split Video Gallery

A split-screen video gallery with scroll-driven transitions.
`,
  "testimonials-split-tabs": `---
title: Testimonials Split Tabs
date: "2026-01-30"
description: A testimonials component with split-panel tabbed navigation
published: true
type: "component"
theme: "dark"
image: "/media/craft/testimonials-split-tabs-light.mp4"
video: "/media/craft/testimonials-split-tabs-light.mp4"
videoDark: "/media/craft/testimonials-split-tabs-dark.mp4"
aspect_ratio: 1.6
---

## Testimonials Split Tabs

A testimonials component with split-panel tabbed navigation.
`
};

/** Precompiled HTML bodies — safe on Cloudflare Workers (no runtime MDX eval). */
export const htmlBySlug: Record<string, string> = {
  "accordion-with-image-tooltip": `<h2 id="accordion-with-image-tooltip">Accordion with Image Tooltip</h2>
<p>An accordion component with image preview tooltips on hover.</p>`,
  "apple-mega-nav": `<h2 id="apple-mega-nav">Apple Mega Nav</h2>
<p>A mega navigation menu inspired by Apple's clean design language.</p>`,
  "bloom-text": `<h2 id="bloom-text">Bloom Text</h2>
<p>A text animation component with a soft bloom and glow reveal effect.</p>`,
  "cta-meteor": `<h2 id="cta-meteor">CTA Meteor</h2>
<p>A call-to-action component with a meteor shower animation effect.</p>`,
  "flicker-footer": `<h2 id="flicker-footer">Flicker Footer</h2>
<p>A footer component with a subtle flicker animation effect.</p>`,
  "hero-bars": `<h2 id="hero-bars">Hero Bars</h2>
<p>An animated hero section with dynamic bar transitions for modern landing pages.</p>`,
  "hero-mobile-showcase": `<h2 id="hero-mobile-showcase">Hero Mobile Showcase</h2>
<p>A mobile-first hero section that showcases app screens with smooth transitions.</p>`,
  "instagram-stories": `<h2 id="instagram-stories">Instagram Stories</h2>
<p>An Instagram-style stories viewer with progress bars and swipe navigation.</p>`,
  "map-location-picker": `<h2 id="map-location-picker">Map Location Picker</h2>
<p>An interactive map-based location picker component.</p>`,
  "models-carousel": `<h2 id="models-carousel">Models Carousel</h2>
<p>A carousel component designed for showcasing 3D models or product imagery.</p>`,
  "project-title-morph": `<h2 id="project-title-morph">Project Title Morph</h2>
<p>A title animation that morphs between project names with smooth transitions.</p>`,
  "scroll-fx-timeline": `<h2 id="scroll-fx-timeline">Scroll FX Timeline</h2>
<p>A timeline component with scroll-driven animation effects.</p>`,
  "scroll-fx": `<h2 id="scroll-fx">Scroll FX</h2>
<p>Scroll-driven visual effects and parallax animations for immersive page experiences.</p>`,
  "scroll-split-video-gallery": `<h2 id="scroll-split-video-gallery">Scroll Split Video Gallery</h2>
<p>A split-screen video gallery with scroll-driven transitions.</p>`,
  "testimonials-split-tabs": `<h2 id="testimonials-split-tabs">Testimonials Split Tabs</h2>
<p>A testimonials component with split-panel tabbed navigation.</p>`
};
