/**
 * Bundle MDX feature content into generated TS modules so Workers never touch the filesystem
 * and never eval MDX at runtime (Workers ban `new Function` / string code generation).
 *
 * Run via `bun run scripts/bundle-mdx-content.ts` (wired into `prebuild` / `build`).
 */
import fs from "node:fs";
import path from "node:path";

import { toHtml } from "hast-util-to-html";
import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { unified } from "unified";

import { parseFrontmatter } from "../src/features/blog/lib/frontmatter";

const roots = [
  {
    contentDir: path.join(process.cwd(), "src/features/blog/content"),
    outFile: path.join(process.cwd(), "src/features/blog/data/content.generated.ts"),
  },
  {
    contentDir: path.join(process.cwd(), "src/features/craft/content"),
    outFile: path.join(process.cwd(), "src/features/craft/data/content.generated.ts"),
  },
] as const;

function escapeTemplateLiteral(raw: string): string {
  return raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function markdownBodyToHtml(body: string): Promise<string> {
  const processor = unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypeSlug);

  const mdast = processor.parse(body);
  const hast = await processor.run(mdast);
  return toHtml(hast);
}

for (const { contentDir, outFile } of roots) {
  if (!fs.existsSync(contentDir)) {
    throw new Error(`Missing content dir: ${contentDir}`);
  }

  const files = fs
    .readdirSync(contentDir)
    .filter((file) => path.extname(file) === ".mdx")
    .sort();

  const rawEntries: string[] = [];
  const htmlEntries: string[] = [];

  for (const file of files) {
    const slug = path.basename(file, ".mdx");
    const raw = fs.readFileSync(path.join(contentDir, file), "utf-8");
    const { content } = parseFrontmatter(raw);
    const html = await markdownBodyToHtml(content);
    rawEntries.push(`  ${JSON.stringify(slug)}: \`${escapeTemplateLiteral(raw)}\``);
    htmlEntries.push(`  ${JSON.stringify(slug)}: \`${escapeTemplateLiteral(html)}\``);
  }

  const body = `/* eslint-disable */
// AUTO-GENERATED by scripts/bundle-mdx-content.ts — do not edit by hand.
export const rawMdxBySlug: Record<string, string> = {
${rawEntries.join(",\n")}
};

/** Precompiled HTML bodies — safe on Cloudflare Workers (no runtime MDX eval). */
export const htmlBySlug: Record<string, string> = {
${htmlEntries.join(",\n")}
};
`;

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body, "utf-8");
  console.log(`Wrote ${files.length} MDX → ${path.relative(process.cwd(), outFile)}`);
}
